name: Build & Test

on:
  push:
    branches: [main, master]

  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build
        run: |
          xcodebuild \
          -project Budgetting.xcodeproj \
          -scheme Budgetting \
          -destination "platform=macOS" \
          CODE_SIGNING_ALLOWED=NO \
          MACOSX_DEPLOYMENT_TARGET=26.2 \
          build

      - name: Run Tests
        run: |
          xcodebuild \
          -project Budgetting.xcodeproj \
          -scheme Budgetting \
          -destination "platform=macOS" \
          CODE_SIGNING_ALLOWED=NO \
          MACOSX_DEPLOYMENT_TARGET=26.2 \
          test
